"""Generate FEATURES.md from the feature registry.

The registry is the single source of truth, so the spec cannot drift from the
code. Run this after adding or changing a feature:

    python build_docs.py
"""

from __future__ import annotations

from pathlib import Path

from promptfeat import REGISTRY, explain_prompt
from promptfeat.engine import compute
from promptfeat.registry import (
    GROUP_BLURBS,
    GROUP_TITLES,
    STATUS_LABELS,
    features_by_group,
    top_features,
)
from promptfeat import nlp

OUTPUT = Path(__file__).resolve().parent / "FEATURES.md"

HEADER = """# Prompt features

Every feature is computed from **only the prompt string**. No model name, no
retrieved documents, no gold answer.

Keep a feature only if you can finish this sentence:

> If this value is high / true, retrieval is more likely to fail because ...

**This file is generated.** Edit the feature declaration in `promptfeat/f_*.py`
and run `python build_docs.py`; do not edit this file by hand. Each card below
states what we see, how it is calculated, a worked example with the value the
code actually returns, when the feature cannot be computed, and why it matters
for retrieval.

## Statuses

A feature that cannot be honestly measured says so instead of returning 0,
because a zero would teach a downstream model something false.

| status | meaning |
| --- | --- |
| `ok` | computed normally |
| `not_applicable` | the prompt has nothing of this kind to measure |
| `undefined` | the formula has no value here, e.g. a ratio with a zero denominator |
| `unreliable` | computed, but outside the range where the metric is meaningful |
| `unavailable` | the backend the feature needs is not installed |

`extract_features(prompt)` returns `None` for anything that is not `ok` or
`unreliable`. `extract_features(prompt, with_status=True)` adds
`<name>__status` and `<name>__reason` so the reason travels with the data.
"""


def _fmt_value(value) -> str:
    if value is None:
        return "`None`"
    if isinstance(value, bool):
        return f"`{value}`"
    if isinstance(value, str):
        return f"`{value!r}`"
    return f"`{value}`"


def _worked_example(feature) -> list[str]:
    if not feature.example:
        return []
    _, ctx = compute(feature.example)
    result = ctx.results.get(feature.name)
    lines = [f"- **Example:** `{feature.example!r}` -> {_fmt_value(result.value if result else None)}"]
    if result and result.status != "ok":
        lines.append(
            f"  - status `{result.status}` ({STATUS_LABELS[result.status]}): {result.reason}"
        )
    if result and result.steps:
        lines.append("  - how that number was reached:")
        for step in result.steps[:6]:
            lines.append(f"    - {step}")
    return lines


def _card(feature) -> str:
    lines = [f"### `{feature.name}`", ""]
    if feature.tier == 1:
        lines.append(f"> **Tier 1, rank {feature.rank} of 30.** {feature.rank_reason}")
        lines.append("")
    lines.append(f"- **What we see:** {feature.summary}")
    lines.append(f"- **Type:** `{feature.dtype}`" + (f", range {feature.value_range}" if feature.value_range else ""))
    lines.append(f"- **Computed by:** {feature.backend}")
    lines.append(f"- **How it is calculated:** {feature.formula}")
    if feature.needs:
        lines.append(
            "- **Built from:** " + ", ".join(f"`{n}`" for n in feature.needs)
        )
    lines.extend(_worked_example(feature))
    if feature.status_rules:
        lines.append("- **When it cannot be computed:**")
        for rule in feature.status_rules:
            lines.append(f"  - {rule}")
    else:
        lines.append("- **When it cannot be computed:** always computable for any prompt.")
    lines.append(f"- **Why retrieval:** {feature.why}")
    lines.append("")
    return "\n".join(lines)


def build() -> str:
    ranked = top_features()
    groups = features_by_group()
    backends = nlp.backend_report()

    parts = [HEADER, ""]

    parts.append("## Backends")
    parts.append("")
    parts.append("| backend | available | version | used for |")
    parts.append("| --- | --- | --- | --- |")
    used_for = {
        "spacy": "entities, POS tags, sentences, dependency parse",
        "wordfreq": "Zipf word frequencies",
        "langdetect": "language identification",
        "tiktoken": "BPE token counts",
        "textstat": "readability formulas and syllable counts",
    }
    for name, info in backends.items():
        mark = "yes" if info["available"] else "no"
        version = info.get("version") or "-"
        parts.append(f"| `{name}` | {mark} | {version} | {used_for.get(name, '')} |")
    parts.append("")
    parts.append(
        "A missing backend never breaks extraction: the features that depend on it "
        "return `None` with status `unavailable` and an install hint."
    )
    parts.append("")

    parts.append(f"## The 30 most important features")
    parts.append("")
    parts.append(
        "Ranked by expected power to predict retrieval failure, chosen to cover "
        "distinct failure modes with as little redundancy as possible. No labelled "
        "retrieval-failure data exists for this project yet, so this ranking is a "
        "judgement call; the `tier` and `rank` fields in the registry are one edit "
        "away from being re-derived by permutation importance once labels exist. "
        "`retrieval_difficulty_score` deliberately sits outside the ranking, because "
        "it is a blend of these features rather than a measurement of its own."
    )
    parts.append("")
    parts.append("| rank | feature | what it catches |")
    parts.append("| --- | --- | --- |")
    for feature in ranked:
        parts.append(f"| {feature.rank} | [`{feature.name}`](#{feature.name.replace('_', '-')}) | {feature.rank_reason} |")
    parts.append("")

    parts.append("## All features by group")
    parts.append("")
    parts.append(f"{len(REGISTRY)} features in {len(groups)} groups.")
    parts.append("")
    for key, members in groups:
        parts.append(f"- **{GROUP_TITLES[key]}** ({len(members)}): " + ", ".join(f"`{f.name}`" for f in members))
    parts.append("")

    for key, members in groups:
        parts.append("---")
        parts.append("")
        parts.append(f"## {GROUP_TITLES[key]}")
        parts.append("")
        parts.append(f"_{GROUP_BLURBS[key]}_")
        parts.append("")
        for feature in members:
            parts.append(_card(feature))

    parts.append("---")
    parts.append("")
    parts.append("## How to get features from a prompt")
    parts.append("")
    parts.append("```python")
    parts.append("from features import extract_features, extract_top_features")
    parts.append("")
    parts.append('extract_features("Who wrote The Hobbit?")')
    parts.append('extract_top_features("Who wrote The Hobbit?")  # the 30 above')
    parts.append('extract_features("Who wrote The Hobbit?", with_status=True)  # + why')
    parts.append("```")
    parts.append("")
    parts.append(
        "Use `enrich.py` for a CSV with a `question` column, `explain.py` for a "
        "per-prompt Markdown report, and `app.py` for the web view where every "
        "number can be expanded into the calculation above."
    )
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    text = build()
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(text.splitlines())} lines, {len(REGISTRY)} features)")


if __name__ == "__main__":
    main()
